name: KuksoItems
version: ${version}
main: com.kukso.minecraft.items.Main
api-version: '1.21'
load: POSTWORLD
authors: [ DevBD1 ]
description: Custom item framework driven by items.yml.
website: https://kukso.com
softdepend: [KuksoLib]
commands:
  giveitem:
    description: Gives a custom item from items.yml
    usage: /giveitem <item-key>
    permission: kuksoitems.giveitem
