name: KuksoWorlds
main: com.kukso.minecraft.worlds.Main
version: ${version}
api-version: '1.21'
load: POSTWORLD
authors: [ DevBD1 ]
description: Lightweight custom world manager with essential features.
website: https://kukso.com
depend:
  - KuksoLib
softdepend:
  - PlaceholderAPI
# You can manage each subcommand in config.yml
commands:
  kuksoworlds:
    usage: /kuksoworlds <subcommand>
    permission: kuksoworlds.command.root
    description: KuksoWorlds main command
    aliases: [kw]
# Permissions are dynamically set for each command in config.yml
permissions:
  kuksoworlds.command.root:
    description: Use it with specific perm(s) of a subcommand