name: KuksoDialogs
version: ${version}
main: com.kukso.minecraft.dialogs.Main
api-version: '1.21'
load: STARTUP
authors: [ DevBD1 ]
description: Create custom screens.
website: https://kukso.com
softdepend:
  - PlaceholderAPI
commands:
  kuksodialogs:
    aliases: [cdia]
    permission: kuksodialogs.command.main
    permission-message: You don't have permission to use this command.
    usage: /<command>
permissions:
  kuksodialogs.command.main:
    default: true
    description: Allows you to use the main command.
  kuksodialogs.admin.version:
    default: op
    description: Allows you to see the plugin version.
  kuksodialogs.admin.reload:
    default: op
    description: Allows you to reload the plugin.
  kuksodialogs.admin.open:
    default: op
    description: Allows you to open dialogs.
  kuksodialogs.admin.validate:
    default: op
    description: Allows you to validate dialogs.
  kuksodialogs.admin.help:
    default: op
    description: Allows you to see the help.
  kuksodialogs.admin.forceopen:
    default: op
    description: Allows you to force open dialogs for others.
  kuksodialogs.admin.forceclose:
    default: op
    description: Allows you to force close dialogs for others.
